### ISSUE TITLE
Getting 403 forbidden while trying to use the tool.

### ISSUE THREAD

**Issue by yidag11** [CompassionAI/lotsawa#1]
Hello, I came across this tool and would really love to use it. Here is the full error I am getting:

[2023-11-08 23:43:29,916][cai_common.models.utils][ERROR] - Failed to download https://compassionai.s3.amazonaws.com/public/data-registry/champion_models\olive-cormorant-nllb-pooled-context-cased\base-600M/manifest.yaml to C:\Users\HP/.cache\torch\hub\champion_models\olive-cormorant-nllb-pooled-context-cased\base-600M\manifest.yaml
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\lotsawa\translate.py", line 103, in main
    translator = Translator(os.path.join(cfg.model.model_ckpt, cfg.model.model_size))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cai_garland\utils\translator.py", line 57, in __init__
    local_ckpt = get_local_ckpt(model_ckpt, model_dir=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cai_common\models\utils.py", line 128, in get_local_ckpt
    model_name = get_local_model_dir(model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cai_common\models\utils.py", line 68, in get_local_model_dir
    _download_file(f"{s3_model_loc}/manifest.yaml", manifest_fn)
  File "C:\Python311\Lib\site-packages\cai_common\models\utils.py", line 25, in _download_file
    raise e
  File "C:\Python311\Lib\site-packages\cai_common\models\utils.py", line 22, in _download_file
    download_url_to_file(s3_loc, target_fn)
  File "C:\Python311\Lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Could you please help? or provide some insight?

**Comment by yidag11** [comment]
I tried again in my ubuntu OS. Works perfectly!! I donot know if this is a windows only issue.
